server:
   port: 8277
   servlet:
      session:
         timeout: 20m
         cookie:
            http-only: true
            secure: true
   compression:
      enabled: true
      min-response-size: 1024
   jetty:
      threads:
         min: 2
         max: 20
      idle-timeout: 15s
      accesslog:
         enabled: true
         directory: logs
         filename: jetty-access.log
         format: NCSA # <- let Jetty supply a valid NCSA string
spring:
   application:
      name: nasb1995edv3
   servlet:
      multipart:
         max-file-size: 2MB
   datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://database-1.cdd6uaafebcj.ap-northeast-1.rds.amazonaws.com:5432/nasb1995?reWriteBatchedInserts=true
      username: postgres
      password: postgres
      hikari:
         maximum-pool-size: 40
         minimum-idle: 10
         connection-timeout: 30000
         max-lifetime: 1200000
         leak-detection-threshold: 20000
   freemarker:
      charset: UTF-8
      allow-request-override: true
      allow-session-override: true
      template-loader-path: classpath:/templates/
      suffix: .ftlh
      settings:
         datetimeFormat: yyyy-MM-dd HH:mm:ss
         templateUpdateDelay: 0ms
   profiles:
      active: prod