server:
  port: 8277
spring:
  application:
    name: nasb1995edv3
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://52.198.76.7:5432/nasb1995
    username: postgres
    password: postgres
    hikari:
      maximum-pool-size: 10
      max-lifetime: 1200000
  thymeleaf:
    cache: false
    mode: HTML
    encoding: UTF-8
    servlet:
      content-type: text/html
    prefix: classpath:/templates/
    suffix: .html
  output:
    ansi:
      enabled: ALWAYS
  profiles:
    active: dev