/*
 * This file is generated by jOOQ.
 */
package app.preach.gospel.jooq.tables.records;


import app.preach.gospel.jooq.tables.Phrases;

import org.jooq.Field;
import org.jooq.Record1;
import org.jooq.Record6;
import org.jooq.Row6;
import org.jooq.impl.UpdatableRecordImpl;


/**
 * This class is generated by jOOQ.
 */
@SuppressWarnings({ "all", "unchecked", "rawtypes", "this-escape" })
public class PhrasesRecord extends UpdatableRecordImpl<PhrasesRecord> implements Record6<Long, String, String, String, Integer, Boolean> {

    private static final long serialVersionUID = 1L;

    /**
     * Setter for <code>public.phrases.id</code>. 節ID
     */
    public void setId(Long value) {
        set(0, value);
    }

    /**
     * Getter for <code>public.phrases.id</code>. 節ID
     */
    public Long getId() {
        return (Long) get(0);
    }

    /**
     * Setter for <code>public.phrases.name</code>. 節名称
     */
    public void setName(String value) {
        set(1, value);
    }

    /**
     * Getter for <code>public.phrases.name</code>. 節名称
     */
    public String getName() {
        return (String) get(1);
    }

    /**
     * Setter for <code>public.phrases.text_en</code>. 内容
     */
    public void setTextEn(String value) {
        set(2, value);
    }

    /**
     * Getter for <code>public.phrases.text_en</code>. 内容
     */
    public String getTextEn() {
        return (String) get(2);
    }

    /**
     * Setter for <code>public.phrases.text_jp</code>. 日本語内容
     */
    public void setTextJp(String value) {
        set(3, value);
    }

    /**
     * Getter for <code>public.phrases.text_jp</code>. 日本語内容
     */
    public String getTextJp() {
        return (String) get(3);
    }

    /**
     * Setter for <code>public.phrases.chapter_id</code>. 章節ID
     */
    public void setChapterId(Integer value) {
        set(4, value);
    }

    /**
     * Getter for <code>public.phrases.chapter_id</code>. 章節ID
     */
    public Integer getChapterId() {
        return (Integer) get(4);
    }

    /**
     * Setter for <code>public.phrases.change_line</code>. 改行フラグ
     */
    public void setChangeLine(Boolean value) {
        set(5, value);
    }

    /**
     * Getter for <code>public.phrases.change_line</code>. 改行フラグ
     */
    public Boolean getChangeLine() {
        return (Boolean) get(5);
    }

    // -------------------------------------------------------------------------
    // Primary key information
    // -------------------------------------------------------------------------

    @Override
    public Record1<Long> key() {
        return (Record1) super.key();
    }

    // -------------------------------------------------------------------------
    // Record6 type implementation
    // -------------------------------------------------------------------------

    @Override
    public Row6<Long, String, String, String, Integer, Boolean> fieldsRow() {
        return (Row6) super.fieldsRow();
    }

    @Override
    public Row6<Long, String, String, String, Integer, Boolean> valuesRow() {
        return (Row6) super.valuesRow();
    }

    @Override
    public Field<Long> field1() {
        return Phrases.PHRASES.ID;
    }

    @Override
    public Field<String> field2() {
        return Phrases.PHRASES.NAME;
    }

    @Override
    public Field<String> field3() {
        return Phrases.PHRASES.TEXT_EN;
    }

    @Override
    public Field<String> field4() {
        return Phrases.PHRASES.TEXT_JP;
    }

    @Override
    public Field<Integer> field5() {
        return Phrases.PHRASES.CHAPTER_ID;
    }

    @Override
    public Field<Boolean> field6() {
        return Phrases.PHRASES.CHANGE_LINE;
    }

    @Override
    public Long component1() {
        return getId();
    }

    @Override
    public String component2() {
        return getName();
    }

    @Override
    public String component3() {
        return getTextEn();
    }

    @Override
    public String component4() {
        return getTextJp();
    }

    @Override
    public Integer component5() {
        return getChapterId();
    }

    @Override
    public Boolean component6() {
        return getChangeLine();
    }

    @Override
    public Long value1() {
        return getId();
    }

    @Override
    public String value2() {
        return getName();
    }

    @Override
    public String value3() {
        return getTextEn();
    }

    @Override
    public String value4() {
        return getTextJp();
    }

    @Override
    public Integer value5() {
        return getChapterId();
    }

    @Override
    public Boolean value6() {
        return getChangeLine();
    }

    @Override
    public PhrasesRecord value1(Long value) {
        setId(value);
        return this;
    }

    @Override
    public PhrasesRecord value2(String value) {
        setName(value);
        return this;
    }

    @Override
    public PhrasesRecord value3(String value) {
        setTextEn(value);
        return this;
    }

    @Override
    public PhrasesRecord value4(String value) {
        setTextJp(value);
        return this;
    }

    @Override
    public PhrasesRecord value5(Integer value) {
        setChapterId(value);
        return this;
    }

    @Override
    public PhrasesRecord value6(Boolean value) {
        setChangeLine(value);
        return this;
    }

    @Override
    public PhrasesRecord values(Long value1, String value2, String value3, String value4, Integer value5, Boolean value6) {
        value1(value1);
        value2(value2);
        value3(value3);
        value4(value4);
        value5(value5);
        value6(value6);
        return this;
    }

    // -------------------------------------------------------------------------
    // Constructors
    // -------------------------------------------------------------------------

    /**
     * Create a detached PhrasesRecord
     */
    public PhrasesRecord() {
        super(Phrases.PHRASES);
    }

    /**
     * Create a detached, initialised PhrasesRecord
     */
    public PhrasesRecord(Long id, String name, String textEn, String textJp, Integer chapterId, Boolean changeLine) {
        super(Phrases.PHRASES);

        setId(id);
        setName(name);
        setTextEn(textEn);
        setTextJp(textJp);
        setChapterId(chapterId);
        setChangeLine(changeLine);
        resetChangedOnNotNull();
    }
}
